#include "batgen.h"
#include <fstream>
#include <cstring>

// 修复：统一为CP_UTF8，与scanner.cpp中的WToA一致，确保SaveBatchFile的UTF8→GB2312转换正确
static std::string WToA(const std::wstring& ws) {
    if (ws.empty()) return "";
    int len = WideCharToMultiByte(CP_UTF8, 0, ws.c_str(), -1, nullptr, 0, nullptr, nullptr);
    if (len <= 0) return "";
    std::string s(len - 1, '\0');
    WideCharToMultiByte(CP_UTF8, 0, ws.c_str(), -1, &s[0], len, nullptr, nullptr);
    return s;
}

std::string GenerateBatch(const ScanResult& result, const BatchOptions& options) {
    std::string sb;
    std::string fname = WToA(result.fileName);

    // Header comments
    if (options.includeComments) {
        sb += "@REM ============================================================\r\n";
        sb += "@REM Silent install script - generated by SilentParamQuery\r\n";
        sb += "@REM File: " + fname + "\r\n";
        sb += "@REM Installer: " + result.installerFullName + "\r\n";
        sb += "@REM Detection: " + result.detectedBy + "\r\n";
        sb += "@REM ============================================================\r\n";
        sb += "\r\n";
    }

    sb += "@echo off\r\n";
    sb += "chcp 936 >nul 2>&1\r\n";
    sb += "\r\n";

    // UAC elevation
    if (options.includeUac) {
        sb += "@REM Request admin privileges\r\n";
        sb += "NET SESSION >nul 2>&1\r\n";
        sb += "IF %ERRORLEVEL% NEQ 0 (\r\n";
        sb += "    echo Requesting admin privileges...\r\n";
        sb += "    powershell -Command \"Start-Process '%~f0' -Verb RunAs\"\r\n";
        sb += "    exit /b\r\n";
        sb += ")\r\n";
        sb += "\r\n";
    }

    // Installer path
    sb += "set \"INSTALLER=%~dp0" + fname + "\"\r\n";
    sb += "\r\n";

    // Error handling preamble
    if (options.includeErrorHandling) {
        sb += "if not exist \"%INSTALLER%\" (\r\n";
        sb += "    echo [ERROR] Installer not found: %INSTALLER%\r\n";
        sb += "    pause\r\n";
        sb += "    exit /b 1\r\n";
        sb += ")\r\n";
        sb += "\r\n";
        sb += "echo ============================================================\r\n";
        sb += "echo  Installing: " + fname + "\r\n";
        sb += "echo  Type: " + result.installerFullName + "\r\n";
        sb += "echo ============================================================\r\n";
        sb += "\r\n";
    }

    // Install command
    std::string installCmd = result.silentCommand;
    // Replace {file} with %INSTALLER%
    {
        size_t pos = installCmd.find("{file}");
        if (pos != std::string::npos)
            installCmd.replace(pos, 6, "%INSTALLER%");
    }

    // Log mode override
    if (options.includeLog) {
        std::string logPath = "%~dp0install_log.txt";
        if (result.installerType == "MSI" || result.installerType == "WiXMSI") {
            installCmd = "msiexec /i \"%INSTALLER%\" /qn /norestart /l*v \"" + logPath + "\"";
        } else if (result.installerType == "InnoSetup") {
            installCmd = "\"%INSTALLER%\" /VERYSILENT /SP- /LOG=\"" + logPath + "\"";
        } else if (result.installerType == "InstallShield" || result.installerType == "InstallScript") {
            installCmd = "\"%INSTALLER%\" /s /v\"/qn /l*v " + logPath + "\"";
        } else if (result.installerType == "BitRockInstallBuilder") {
            installCmd = "\"%INSTALLER%\" --mode unattended --debuglevel 4";
        }
    }

    sb += "echo Installing...\r\n";
    sb += installCmd + "\r\n";
    sb += "\r\n";

    // Error checking
    if (options.includeErrorHandling) {
        sb += "if %ERRORLEVEL% EQU 0 (\r\n";
        sb += "    echo [SUCCESS] Installation complete\r\n";
        sb += ") else (\r\n";
        sb += "    echo [FAILED] Installation error, code: %ERRORLEVEL%\r\n";
        sb += "    pause\r\n";
        sb += "    exit /b %ERRORLEVEL%\r\n";
        sb += ")\r\n";
        sb += "\r\n";
    }

    if (options.includeLog) {
        sb += "echo Log saved to: install_log.txt\r\n";
    }

    sb += "echo Installation complete.\r\n";
    sb += "exit /b 0\r\n";

    return sb;
}

bool SaveBatchFile(const std::string& content, const std::wstring& filePath) {
    // Convert UTF-8 content to GB2312 (code page 936) for batch file compatibility
    // First convert UTF-8 to wide
    int wideLen = MultiByteToWideChar(CP_UTF8, 0, content.c_str(), -1, nullptr, 0);
    if (wideLen <= 0) return false;
    std::wstring wide(wideLen - 1, L'\0');
    MultiByteToWideChar(CP_UTF8, 0, content.c_str(), -1, &wide[0], wideLen);

    // Then convert wide to GB2312
    int ansiLen = WideCharToMultiByte(936, 0, wide.c_str(), -1, nullptr, 0, nullptr, nullptr);
    if (ansiLen <= 0) return false;
    std::string ansi(ansiLen - 1, '\0');
    WideCharToMultiByte(936, 0, wide.c_str(), -1, &ansi[0], ansiLen, nullptr, nullptr);

    FILE* f = _wfopen(filePath.c_str(), L"wb");
    if (!f) return false;
    fwrite(ansi.data(), 1, ansi.size(), f);
    fclose(f);
    return true;
}
